/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Clases.Expediente;
import Clases.GestionExpediente;
import Clases.Nodo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class Menu extends javax.swing.JFrame {
    private GestionExpediente gestionExp;
    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        gestionExp = new GestionExpediente();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TListaExpedientes = new javax.swing.JTable();
        BAgreagar = new javax.swing.JButton();
        Bmostrar = new javax.swing.JButton();
        BMover = new javax.swing.JButton();
        BEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TListaExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TListaExpedientes);

        BAgreagar.setText("Agregar Expediente");
        BAgreagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgreagarActionPerformed(evt);
            }
        });

        Bmostrar.setText("Mostrar Expedientes");
        Bmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmostrarActionPerformed(evt);
            }
        });

        BMover.setText("Mover Expediente");
        BMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMoverActionPerformed(evt);
            }
        });

        BEliminar.setText("Eliminar Expediente");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BMover, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAgreagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bmostrar)
                    .addComponent(BEliminar))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAgreagar)
                    .addComponent(Bmostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMover)
                    .addComponent(BEliminar))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgreagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgreagarActionPerformed
        AgregarExpediente A = new AgregarExpediente(gestionExp);
        A.setVisible(true);
        
    }//GEN-LAST:event_BAgreagarActionPerformed

    private void BmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmostrarActionPerformed
        DefaultTableModel modelo_tabla = new DefaultTableModel();
        this.TListaExpedientes.setModel(modelo_tabla);
        modelo_tabla.addColumn("ID");
        modelo_tabla.addColumn("Asunto");
        modelo_tabla.addColumn("Documento");
        modelo_tabla.addColumn("Prioridad");
        modelo_tabla.addColumn("DNI");
        modelo_tabla.addColumn("Nombre");
        modelo_tabla.addColumn("Telefono");
        modelo_tabla.addColumn("Correo");
        modelo_tabla.addColumn("Ubicacion");
        
        Expediente Eaux = new Expediente(0,0,"","",0,"","","");
        GestionExpediente aux = new GestionExpediente();
        int count = 0;
        while(!gestionExp.esVacia()){
            Eaux = (Expediente)gestionExp.desencolar();
            aux.encolar(Eaux);
            modelo_tabla.insertRow(count, new Object[]{
                Eaux.getId(),
                Eaux.getAsunto(),
                Eaux.getDocumento(),
                Eaux.getPrioridad(),
                Eaux.getDni(),
                Eaux.getNombre(),
                Eaux.getTelefono(),
                Eaux.getCorreo(),
            });
            count++;
            aux.encolar(Eaux);
        }
        while(!aux.esVacia()){
            gestionExp.encolar(aux.desencolar());
        }
        
        
    }//GEN-LAST:event_BmostrarActionPerformed

    private void BMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMoverActionPerformed
        Expediente Eaux = new Expediente(0,0,"","",0,"","","");
        
    }//GEN-LAST:event_BMoverActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila = TListaExpedientes.getSelectedRow();
        if (fila >= 0) {
            DefaultTableModel modelo = (DefaultTableModel) TListaExpedientes.getModel();
            modelo.removeRow(fila); 
        } else {
            JOptionPane.showMessageDialog(null, "No hay fila seleccionada");
        }
    }//GEN-LAST:event_BEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgreagar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BMover;
    private javax.swing.JButton Bmostrar;
    private javax.swing.JTable TListaExpedientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
